/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.QuanLyDiemDAO;
import Model.SinhVien;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author XUÂN THÀNH
 */
public class QuanLyDiemPanel extends javax.swing.JPanel {
    
    private int listIndex = -1;
    private ArrayList<SinhVien> listSV;
    private DefaultTableModel dtm;
    private QuanLyDiemDAO qld;

    /**
     * Creates new form QuanLyDiemPanel
     */
    public QuanLyDiemPanel() {
        initComponents();
        
        
        this.qld = new QuanLyDiemDAO();
        
        this.listSV = new ArrayList<>();
        this.dtm = (DefaultTableModel) tblQLD.getModel();
        try {
            this.listSV = this.qld.getDanhSachSV();
        } catch (Exception ex) {
            Logger.getLogger(QuanLyDiemPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        doiMauChuTitle();
        GioHeThong();
        chuChay();
        fillTable(0);
    }

    public void doiMauChuTitle() {
        Runnable setColorTitle = new Runnable() {
            @Override
            public void run() {
                int i = 0;
                while (true) {
                    if (i > 15) {
                        i = 0;
                    }
                    if (i == 0) {
                        lblTitle.setForeground(Color.red);
                    }

                    if (i == 5) {
                        lblTitle.setForeground(Color.BLUE);
                    }

                    if (i == 10) {
                        lblTitle.setForeground(Color.black);
                    }

                    i++;
                    try {
                        Thread.sleep(300);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(QuanLySinhVienPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
        };

        Thread t = new Thread(setColorTitle);
        t.start();
    }

    public void GioHeThong() {
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    Calendar now = Calendar.getInstance();
                    int h = now.get(Calendar.HOUR);
                    int m = now.get(Calendar.MINUTE);
                    int s = now.get(Calendar.SECOND);

                    lblOclock.setText(h + ":" + m + ":" + s);
                }
            }

        }.start();
    }

    public void chuChay() {
        new Thread() {
            @Override
            public void run() {
                String txt = lblChayChu.getText();
                while (true) {
                    txt = txt.substring(1, txt.length()) + txt.charAt(0);
                    lblChayChu.setText(txt);
                    try {
                        Thread.sleep(320);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(QuanLyDiemPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblErrorTiengAnh = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblDiemTB = new javax.swing.JLabel();
        lblHienThiDTB = new javax.swing.JLabel();
        txtTiengAnh = new javax.swing.JTextField();
        lblTiengAnh = new javax.swing.JLabel();
        lblErrorTinHoc = new javax.swing.JLabel();
        txtTinHoc = new javax.swing.JTextField();
        lblTinHoc = new javax.swing.JLabel();
        lblErrorGDTC = new javax.swing.JLabel();
        lblGDTC = new javax.swing.JLabel();
        txtGDTC = new javax.swing.JTextField();
        lblHoTen = new javax.swing.JLabel();
        lblSetHoTen = new javax.swing.JLabel();
        lblMaSV = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        lblErrorMa = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnTaoMoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhap = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPre = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQLD = new javax.swing.JTable();
        lblTop3SV = new javax.swing.JLabel();
        lblOclock = new javax.swing.JLabel();
        lblChayChu = new javax.swing.JLabel();
        cbbHienThi = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(240, 240, 191));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("QUẢN LÝ ĐIỂM SINH VIÊN");

        jPanel2.setBackground(new java.awt.Color(240, 240, 191));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Tìm Kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        lblTimKiem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTimKiem.setText("Nhập Mã SV:");

        btnTimKiem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Search.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnTimKiem)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimKiem)
                        .addComponent(btnTimKiem))
                    .addComponent(lblTimKiem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblErrorTiengAnh.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        lblErrorTiengAnh.setForeground(new java.awt.Color(255, 51, 51));

        lblDiemTB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDiemTB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiemTB.setText("Điểm TB:");

        lblHienThiDTB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblHienThiDTB.setForeground(new java.awt.Color(0, 0, 255));
        lblHienThiDTB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHienThiDTB.setText("9.5");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiemTB, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(lblHienThiDTB, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHienThiDTB, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        lblTiengAnh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTiengAnh.setText("Tiếng anh:");

        lblErrorTinHoc.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        lblErrorTinHoc.setForeground(new java.awt.Color(255, 51, 51));

        lblTinHoc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTinHoc.setText("Tin học:");

        lblErrorGDTC.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        lblErrorGDTC.setForeground(new java.awt.Color(255, 51, 51));

        lblGDTC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGDTC.setText("Giáo dục TC:");

        lblHoTen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHoTen.setText("Họ Tên SV:");

        lblSetHoTen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSetHoTen.setForeground(new java.awt.Color(0, 51, 255));

        lblMaSV.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaSV.setText("Mã SV:");

        txtMa.setForeground(new java.awt.Color(0, 204, 204));

        lblErrorMa.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        lblErrorMa.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSetHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblTinHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTinHoc, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblGDTC, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtGDTC))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lblErrorGDTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTiengAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorMa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTiengAnh, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblErrorTiengAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrorTinHoc, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblGDTC, lblMaSV, lblTiengAnh, lblTinHoc});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSetHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblErrorMa, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaSV)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblErrorTiengAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTiengAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTiengAnh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorTinHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTinHoc)
                            .addComponent(txtTinHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblErrorGDTC, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGDTC)
                            .addComponent(txtGDTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        btnTaoMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add.png"))); // NOI18N
        btnTaoMoi.setText("Tạo mới  ");
        btnTaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMoiActionPerformed(evt);
            }
        });

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save.png"))); // NOI18N
        btnLuu.setText("Lưu       ");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa        ");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Edit.png"))); // NOI18N
        btnCapNhap.setText("Cập nhập");
        btnCapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTaoMoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCapNhap)
                            .addComponent(btnXoa)
                            .addComponent(btnLuu))))
                .addGap(20, 20, 20))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCapNhap, btnLuu, btnTaoMoi, btnXoa});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTaoMoi)
                .addGap(18, 18, 18)
                .addComponent(btnLuu)
                .addGap(18, 18, 18)
                .addComponent(btnXoa)
                .addGap(18, 18, 18)
                .addComponent(btnCapNhap)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCapNhap, btnLuu, btnXoa});

        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Button-First-icon-24.png"))); // NOI18N
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Button-Previus-icon-24.png"))); // NOI18N
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Button-Forward-icon-48.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Button-Last-icon-24.png"))); // NOI18N
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnFirst)
                .addGap(18, 18, 18)
                .addComponent(btnPre)
                .addGap(18, 18, 18)
                .addComponent(btnNext)
                .addGap(18, 18, 18)
                .addComponent(btnLast)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFirst, btnLast, btnNext, btnPre});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirst)
                    .addComponent(btnPre)
                    .addComponent(btnNext)
                    .addComponent(btnLast))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnFirst, btnLast, btnNext, btnPre});

        tblQLD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SV", "Họ Tên", "Tiếng anh", "Tin Học", "Giáo dục TC", "Điểm TB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblQLD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQLDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQLD);

        lblTop3SV.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTop3SV.setForeground(new java.awt.Color(51, 0, 0));
        lblTop3SV.setText("Hiển Thị: ");

        lblOclock.setBackground(new java.awt.Color(0, 153, 153));
        lblOclock.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblOclock.setForeground(new java.awt.Color(51, 0, 51));
        lblOclock.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOclock.setText("00:00:00");

        lblChayChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChayChu.setText("                               Cô ơi em làm được chữ chạy cô cho em thêm điểm nha! <3                                                    ");

        cbbHienThi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Danh Sách Sinh Viên", "Top sinh viên có điểm cao nhất" }));
        cbbHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbHienThiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblChayChu, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTop3SV)
                .addGap(18, 18, 18)
                .addComponent(cbbHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblOclock, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblChayChu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTop3SV)
                    .addComponent(cbbHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOclock))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoMoiActionPerformed
        clearForm();
    }//GEN-LAST:event_btnTaoMoiActionPerformed

    private void cbbHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbHienThiActionPerformed
        int choice = this.cbbHienThi.getSelectedIndex();
        fillTable(choice);
    }//GEN-LAST:event_cbbHienThiActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String maSV = this.txtTimKiem.getText();
        if (maSV.equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn Phải nhập mã sinh viên");
            return;
        }
        clearForm();
        fillForm(maSV);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblQLDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQLDMouseClicked

        int row = this.tblQLD.getSelectedRow();
        if (row >= 0) {
            String maSV = (String) this.tblQLD.getValueAt(row, 0);
            fillForm(maSV);
        }


    }//GEN-LAST:event_tblQLDMouseClicked

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        if (checkForm() == false)return;
        
        int xn = JOptionPane.showConfirmDialog(this, "Ban có muốn thêm bảng điểm mới cho sinh viên không?");
        if (xn == JOptionPane.YES_OPTION) {
            try {
                if (this.qld.kiemTraSVCoTonTai(getThongTinhSV().getMASV()) != null && this.qld.timTheoMa(getThongTinhSV().getMASV()) == null) {
                    this.qld.insert(getThongTinhSV());
                    JOptionPane.showMessageDialog(this, "Thêm mới thành công");
                    fillTable(this.cbbHienThi.getSelectedIndex());
                    clearForm();
                } else {
                    if(this.qld.kiemTraSVCoTonTai(getThongTinhSV().getMASV()) == null){
                        JOptionPane.showMessageDialog(this, "Mã sinh viên này không tồn tại");
                        return;
                    }
                    JOptionPane.showMessageDialog(this, "Mã sinh viên này đã tồn tại. vui lòng chọn cập nhập nếu bạn muốn sửa thông tin sinh viên");
                    return;
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhapActionPerformed
        if (checkForm() == false)return;
        
        int xn = JOptionPane.showConfirmDialog(this, "Ban có muốn Cập nhập lại bảng điểm cho sinh viên không?");
        if (xn == JOptionPane.YES_OPTION) {
            try {
                if ( this.qld.timTheoMa(getThongTinhSV().getMASV()) != null) {
                    this.qld.update(getThongTinhSV());
                    JOptionPane.showMessageDialog(this, "Cập nhập thành công");
                    fillTable(this.cbbHienThi.getSelectedIndex());
                    clearForm();
                } else {                    
                    JOptionPane.showMessageDialog(this, "Mã sinh viên này đã tồn tại. vui lòng chọn Lưu nếu bạn muốn thêm thông tin mới cho sinh viên");
                    return;
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnCapNhapActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String maSV = txtMa.getText();
        if (maSV.equals("")) {
            maSV = JOptionPane.showInputDialog("Nhập mã sinh viên muốn xóa");
            if (maSV == null)return;
        }
        int xn = JOptionPane.showConfirmDialog(this, "Ban có muốn Xóa bảng điểm của sinh viên này không?");
        if (xn == JOptionPane.YES_OPTION) {
            try {
                if (this.qld.timTheoMa(getThongTinhSV().getMASV()) != null) {
                    this.qld.delete(maSV);
                    JOptionPane.showMessageDialog(this, "Đã xóa thành công");
                    fillTable(cbbHienThi.getSelectedIndex());
                    clearForm();
                } else {
                    JOptionPane.showMessageDialog(this, "Mã sinh viên này không tồn tại");
                    return;
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        if (this.listIndex != 0){
            this.listIndex = 0;
        }
        
        try {
            this.listSV = this.qld.getDanhSachSV();
            String maSV = this.listSV.get(listIndex).getMASV();
            fillForm(maSV);
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
       if (this.listIndex > 0){
            this.listIndex--;
        }
        
        try {
            this.listSV = this.qld.getDanhSachSV();
            String maSV = this.listSV.get(listIndex).getMASV();
            fillForm(maSV);
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnPreActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        
         if (this.listIndex < this.listSV.size()-1){
            this.listIndex++;
        }
        
        try {
            this.listSV = this.qld.getDanhSachSV();
            String maSV = this.listSV.get(listIndex).getMASV();
            fillForm(maSV);
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        if (this.listIndex < this.listSV.size()-1){
            this.listIndex = this.listSV.size()-1;
        }
        
        try {
            this.listSV = this.qld.getDanhSachSV();
            String maSV = this.listSV.get(listIndex).getMASV();
            fillForm(maSV);
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnLastActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhap;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPre;
    private javax.swing.JButton btnTaoMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbHienThi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChayChu;
    private javax.swing.JLabel lblDiemTB;
    private javax.swing.JLabel lblErrorGDTC;
    private javax.swing.JLabel lblErrorMa;
    private javax.swing.JLabel lblErrorTiengAnh;
    private javax.swing.JLabel lblErrorTinHoc;
    private javax.swing.JLabel lblGDTC;
    private javax.swing.JLabel lblHienThiDTB;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMaSV;
    private javax.swing.JLabel lblOclock;
    private javax.swing.JLabel lblSetHoTen;
    private javax.swing.JLabel lblTiengAnh;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblTinHoc;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTop3SV;
    private javax.swing.JTable tblQLD;
    private javax.swing.JTextField txtGDTC;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTiengAnh;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTinHoc;
    // End of variables declaration//GEN-END:variables

    public void fillTable(int choice) {
        this.dtm.setRowCount(0);
        ArrayList<SinhVien> list = new ArrayList<>();
        switch (choice) {
            case 0: {
                try {
                    list = this.qld.getDanhSachSV();
                    addDataForTable(list);
                } catch (Exception ex) {
                    Logger.getLogger(QuanLyDiemPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            break;

            case 1:
                int top = Integer.parseInt(JOptionPane.showInputDialog("Bạn Muốn tìm top mấy?"));
                 {
                    try {

                        list = this.qld.getTopDanhSachSV(top);
                        addDataForTable(list);
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
                break;

        }

    }

    public void addDataForTable(ArrayList<SinhVien> list) {
        for (SinhVien sv : list) {
            float dtb = (sv.getTiengAnh() + sv.getTinHoc() + sv.getGDTC()) / 3;
            Object[] data = new Object[]{
                sv.getMASV(),
                sv.getHoTen(),
                sv.getTiengAnh(),
                sv.getTinHoc(),
                sv.getGDTC(),
                String.format("%.2f", dtb)
            };
            this.dtm.addRow(data);
        }
    }

    public void fillForm(String maSV) {
        SinhVien sv = new SinhVien();
        try {
            sv = this.qld.timTheoMa(maSV);
            if (sv == null) {
                JOptionPane.showMessageDialog(this, "Mã Sinh Viên Không Tồn Tại");
                return;
            }
            this.txtMa.setText(sv.getMASV());
            this.lblSetHoTen.setText(sv.getHoTen());
            this.txtTiengAnh.setText(String.valueOf(sv.getTiengAnh()));
            this.txtTinHoc.setText(String.valueOf(sv.getTinHoc()));
            this.txtGDTC.setText(String.valueOf(sv.getGDTC()));
            float dtb = (sv.getGDTC() + sv.getTiengAnh() + sv.getTinHoc()) / 3;
            this.lblHienThiDTB.setText(String.format("%.2f", dtb));

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    public void clearForm() {
        this.txtGDTC.setText("");
        this.txtMa.setText("");
        this.txtTiengAnh.setText("");
        this.txtTimKiem.setText("");
        this.txtTinHoc.setText("");
        this.lblSetHoTen.setText("");
        this.lblErrorMa.setText("");
        this.lblErrorTinHoc.setText("");
        this.lblErrorTiengAnh.setText("");
        this.lblErrorGDTC.setText("");
        this.txtGDTC.setBackground(Color.white);
        this.txtTinHoc.setBackground(Color.white);
        this.txtTiengAnh.setBackground(Color.white);
        this.txtMa.setBackground(Color.white);
    }

    public boolean checkForm() {
        boolean a = true;

        if (txtMa.getText().equals("")) {
            this.lblErrorMa.setText("Bạn chưa nhập mã sinh viên");
            this.txtMa.setBackground(Color.yellow);
            a = false;
        } else {
            this.lblErrorMa.setText("");
            this.txtMa.setBackground(Color.white);
        }

        if (txtTiengAnh.getText().equals("")) {
            this.lblErrorTiengAnh.setText("Bạn chưa nhập Điểm tiếng anh");
            this.txtTiengAnh.setBackground(Color.yellow);
            a = false;
        } else if (!txtTiengAnh.getText().equals("")) {
            try {
                float diem = Float.parseFloat(txtTiengAnh.getText());
                if (diem > 10 || diem < 0) {
                    this.lblErrorTiengAnh.setText("điểm phải lớn hơn 0 và không lớn hơn 10");
                    this.txtTiengAnh.setBackground(Color.yellow);
                    a = false;
                } else {
                    this.lblErrorTiengAnh.setText("");
                    this.txtTiengAnh.setBackground(Color.white);
                    
                }

            } catch (Exception e) {
                this.lblErrorTiengAnh.setText("Điểm tiếng anh phải là số thực");
                this.txtTiengAnh.setBackground(Color.yellow);
                a = false;
                e.printStackTrace();
            }

        } else {
                    this.lblErrorTiengAnh.setText("");
                    this.txtTiengAnh.setBackground(Color.white);
                    
                }
        
        

        if (txtTinHoc.getText().equals("")) {
            this.lblErrorTinHoc.setText("Bạn chưa nhập Điểm Tin Học");
            this.txtTinHoc.setBackground(Color.yellow);
            a = false;
        } else if (!txtTinHoc.getText().equals("")) {
            try {
                float diem = Float.parseFloat(txtTinHoc.getText());
                if (diem > 10 || diem < 0) {
                    this.lblErrorTinHoc.setText("điểm phải lớn hơn 0 và không lớn hơn 10");
                    this.txtTinHoc.setBackground(Color.yellow);
                    a = false;
                } else {
                    this.lblErrorTinHoc.setText("");
                    this.txtTinHoc.setBackground(Color.white);
                    
                }

            } catch (Exception e) {
                this.lblErrorTinHoc.setText("Điểm tin học phải là số thực");
                this.txtTinHoc.setBackground(Color.yellow);
                a = false;
                e.printStackTrace();
            }

        } else {
                    this.lblErrorTinHoc.setText("");
                    this.txtTinHoc.setBackground(Color.white);
                    
                }

        if (txtGDTC.getText().equals("")) {
            this.lblErrorGDTC.setText("Bạn chưa nhập Điểm GDTC");
            this.txtGDTC.setBackground(Color.yellow);
            a = false;
        } else if (!txtGDTC.getText().equals("")) {
            try {
                float diem = Float.parseFloat(txtGDTC.getText());
                if (diem > 10 || diem < 0) {
                    this.lblErrorGDTC.setText("điểm phải lớn hơn 0 và không lớn hơn 10");
                    this.txtGDTC.setBackground(Color.yellow);
                    a = false;
                } else {
                    this.lblErrorGDTC.setText("");
                    this.txtGDTC.setBackground(Color.white);
                    
                }

            } catch (Exception e) {
                this.lblErrorGDTC.setText("Điểm GDTC phải là số thực");
                this.txtGDTC.setBackground(Color.yellow);
                a = false;
                e.printStackTrace();
            }

        } else {
                    this.lblErrorGDTC.setText("");
                    this.txtGDTC.setBackground(Color.white);
                    
                }

        return a;
    }
    
    public SinhVien getThongTinhSV() {
        String maSV,HoTen;
        HoTen = this.lblSetHoTen.getText();
        maSV = this.txtMa.getText();
        float dTiengAnh = Float.parseFloat(this.txtTiengAnh.getText());
        float dTinHoc = Float.parseFloat(this.txtTinHoc.getText());
        float dGDTC = Float.parseFloat(this.txtGDTC.getText());
        
        SinhVien sv = new SinhVien();
        sv.setTiengAnh(dTiengAnh);
        sv.setTinHoc(dTinHoc);
        sv.setGDTC(dGDTC);
        sv.setHoTen(HoTen);
        sv.setMASV(maSV);
        
        return sv;
    }
}
